#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Polybar
$HOME/.config/polybar/launch_polybar.sh

# Background Image
feh --bg-center ~/Pictures/natures_tree.jpg

# Mouse Acceleration
xinput --set-prop 8 'libinput Accel Speed' -0.5

# Compositor (picom)
picom --config ~/.config/picom/picom.conf -c -b

# Logitech Keyboard LEDs (keyledsd)
keyledsd

# Cursor
xsetroot -cursor_name left_ptr &

