#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Polybar
$HOME/.config/polybar/launch_polybar.sh

# Background Image
feh --bg-fill --no-xinerama ~/Pictures/black_hole.jpg

# Mouse Acceleration
xinput --set-prop 8 'libinput Accel Speed' -0.5

# Compositor (picom)
picom --config ~/.config/picom/picom.conf -c -b

# Cursor
xsetroot -cursor_name left_ptr &

xset -b
